// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
)

// CreateCustomerInput represents a mutation input for creating customers.
type CreateCustomerInput struct {
	Username    string
	Password    string
	Fullname    string
	PhoneNumber int
	Email       string
	IDCard      int
	MemberCard  int
	DateOfBirth time.Time
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}

// Mutate applies the CreateCustomerInput on the CustomerMutation builder.
func (i *CreateCustomerInput) Mutate(m *CustomerMutation) {
	m.SetUsername(i.Username)
	m.SetPassword(i.Password)
	m.SetFullname(i.Fullname)
	m.SetPhoneNumber(i.PhoneNumber)
	m.SetEmail(i.Email)
	m.SetIDCard(i.IDCard)
	m.SetMemberCard(i.MemberCard)
	m.SetDateOfBirth(i.DateOfBirth)
	if v := i.CreatedAt; v != nil {
		m.SetCreatedAt(*v)
	}
	if v := i.UpdatedAt; v != nil {
		m.SetUpdatedAt(*v)
	}
}

// SetInput applies the change-set in the CreateCustomerInput on the CustomerCreate builder.
func (c *CustomerCreate) SetInput(i CreateCustomerInput) *CustomerCreate {
	i.Mutate(c.Mutation())
	return c
}
